name: "My action"
description: "Test my action"

inputs:
  message:
    description: "The message to print"
    required: true
    default: "Hola"

runs:
  using: "composite"

  steps:
    - name: Hola mundo
      run: echo "${{ inputs.message }}"
      shell: bash
